# building a first pipeline
name: My First Git Pipeline
on: [push]
jobs: 
     print-hello-world:
         runs-on: ubuntu-latest
         steps:
          - uses: actions/checkout@v2
          - name: Use Node.js 12
            uses: actions/setup-node@v2
            with:
              node-version: 12
     print-hello-world-2:
         needs: print-hello-world
         runs-on: ubuntu-latest
         steps:
           - run: echo "First Step for Hello world."       
     print-hello-world-3:
         needs: print-hello-world
         runs-on: ubuntu-latest
         steps:
           - run: echo "First Step for Hello world."                  
     print-hello-world-4:
         needs: 
             - print-hello-world-2
             - print-hello-world-3
         runs-on: ubuntu-latest
         steps:
           - run: echo "First Step for Hello world."                     